### ISSUE TITLE
Erro ao fazer transação por cartão de crédito

### ISSUE THREAD

**Issue by RodrigoMacedo7** [pagarme/woocommerce-beta#473]
# Bug

### Descrição

Estamos com um problema na compra por cartão de crédito na loja. Aparentemente, transações por PIX e boleto bancário estão funcionando normalmente. Mas cartão de crédito, a aplicação apresenta erro de código. 

Ocultei o nome do domínio da aplicação, alterando para (nomedaloja). 

### Como reproduzir
Descreva os passos para reproduzir o bug.

Eu acesso a loja, adiciono um produto ao carrinho, e seleciono cartão de crédito para pagamento. O plugin exibe um formulário com os dados do cartão, e ao preencher e clicar no botão de pagar, a aplicação informa este erro.

### Evidências

Warning: Undefined array key "" in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Model/Payment/Card.php on line 106

Warning: Undefined array key "" in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Model/Payment/Card.php on line 107

Warning: Undefined array key "" in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Model/Payment/Card.php on line 108

Warning: Undefined array key "" in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Model/Payment/Card.php on line 109

Warning: Undefined array key "pagarmetoken1" in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Concrete/WoocommercePlatformOrderDecorator.php on line 798

Warning: Undefined array key "card_id" in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Concrete/WoocommercePlatformOrderDecorator.php on line 801

Warning: Undefined array key "brand" in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Concrete/WoocommercePlatformOrderDecorator.php on line 806

Warning: Undefined array key "installments" in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Concrete/WoocommercePlatformOrderDecorator.php on line 812

Fatal error: Uncaught TypeError: Pagarme\Core\Payment\Aggregates\Order::addPayment(): Argument #1 ($payment) must be of type Pagarme\Core\Payment\Aggregates\Payments\AbstractPayment, null given, called in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php on line 376 and defined in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Payment/Aggregates/Order.php:134 Stack trace: #0 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php(376): Pagarme\Core\Payment\Aggregates\Order->addPayment() #1 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Kernel/Services/OrderService.php(252): Pagarme\Core\Kernel\Services\OrderService->extractPaymentOrderFromPlatformOrder() #2 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Controller/Orders.php(64): Pagarme\Core\Kernel\Services\OrderService->createOrderAtPagarme() #3 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Model/Checkout.php(129): Woocommerce\Pagarme\Controller\Orders->create_order() #4 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/src/Controller/Gateways/AbstractGateway.php(199): Woocommerce\Pagarme\Model\Checkout->process() #5 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1062): Woocommerce\Pagarme\Controller\Gateways\AbstractGateway->process_payment() #6 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1293): WC_Checkout->process_order_payment() #7 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/woocommerce/includes/class-wc-form-handler.php(387): WC_Checkout->process_checkout() #8 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-includes/class-wp-hook.php(324): WC_Form_Handler::checkout_action() #9 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters() #10 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-includes/plugin.php(517): WP_Hook->do_action() #11 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-settings.php(722): do_action() #12 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-config.php(99): require_once('/home/u37183576...') #13 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-load.php(50): require_once('/home/u37183576...') #14 /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-blog-header.php(13): require_once('/home/u37183576...') #15 /home/u371835763/domains/(nomedaloja).com.br/public_html/index.php(17): require('/home/u37183576...') #16 {main} thrown in /home/u371835763/domains/(nomedaloja).com.br/public_html/wp-content/plugins/pagarme-payments-for-woocommerce/vendor/pagarme/ecommerce-module-core/src/Payment/Aggregates/Order.php on line 134

Há um erro crítico no seu site.

Saiba mais sobre a como resolver problemas do WordPress.

**Comment by RafaMelazzo** [comment]
Olá @RodrigoMacedo7!

Recebemos seu e-mail com mais detalhes do erro, e acabamos de enviar uma resposta. Vamos acompanhando por lá até encontrarmos uma solução.

Obrigado!
